# -*- coding: utf-8 -*-
"""TABLA CATALOGO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VOKcBHQlq57yGj6J6696rMmnPYNB1Ai

CREACiÓN DE CATALOGO DE PELÍCULAS
"""

import random

def generate_movie_data(movie_id):
    genres = {
        1: "Acción", 2: "Comedia", 3: "Drama", 4: "Ciencia Ficción", 5: "Crimen",
        6: "Aventura", 7: "Fantasía", 8: "Suspenso", 9: "Historia", 10: "Western", 11: "Otro"
    }

    titles = ["Furia Letal", "Risas Infinitas", "El Último Acto", "Galaxia Perdida", "Crimen Perfecto",
              "Expedición Prohibida", "Magia Oscura", "Bajo Sospecha", "El Pasado Olvidado", "Duelo al Amanecer"]
    directors = ["Juan Pérez", "María López", "Carlos Fernández", "Ana Ramírez", "Luis Gómez"]
    writers = ["Sofía Herrera", "Pedro Sánchez", "Gabriel Díaz", "Lucía Ortega", "Fernando Ruiz"]
    languages = ["Español", "Inglés", "Francés", "Alemán", "Italiano"]
    durations = ["90 min", "105 min", "120 min", "135 min", "150 min"]

    title = random.choice(titles)
    genre_id = random.choice(list(genres.keys()))
    description = f"Una historia fascinante de {genres[genre_id].lower()} que atrapa desde el primer minuto."
    image = f"{title.lower().replace(' ', '_')}.jpg"
    acclaimed = random.choice([0, 1])
    director = random.choice(directors)
    writer = random.choice(writers)
    duration = random.choice(durations)
    language = random.choice(languages)
    trailer = f"https://www.youtube.com/watch?v={random.randint(100000, 999999)}"
    release_date = f"{random.randint(2000, 2025)}-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}"
    revenue = f"${random.randint(1000000, 500000000):,}"
    budget = f"${random.randint(500000, 200000000):,}"
    banner = f"banner_{title.lower().replace(' ', '_')}.jpg"

    return (movie_id, title, description, image, acclaimed, genre_id, director, writer, duration, language,
            trailer, release_date, revenue, budget, banner)

def generate_sql_insert(num_movies=10):
    values = []
    for i in range(1, num_movies + 1):
        data = generate_movie_data(i)
        values.append("({}, '{}', '{}', '{}', {}, {}, '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}')".format(*data))

    sql = ("INSERT INTO catalogo (CATALOGO_ID, NOMBRES, DESCRIPCION, IMG, ACLAMADO, GENERO_PELICULAS_ID, DIRECTOR, "
           "ESCRITOR, DURACION, IDIOMA, TRAILER, ESTRENO, RECAUDACION, PRESUPUESTO, BANNER) VALUES \n" + ",\n".join(values) + ";")

    return sql

if __name__ == "__main__":
    print(generate_sql_insert(9300))