# -*- coding: utf-8 -*-
"""TABLA USUARIOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM_BYPv7sy0LPkdumSv4RBfQEadFTBZi

CREACIÓN DE USUARIOS ADMINISTRADORES
"""

import random

# Datos de ejemplo
nombres = ["Juan", "María", "Carlos", "Laura", "Pedro", "Sofía", "Fernando", "Lucía", "Martín", "Valentina"]
apellidos = ["Gomez", "Perez", "Fernandez", "Rodriguez", "Lopez", "Diaz", "Martinez", "Sanchez", "Romero", "Vega"]
paises = ["Argentina", "México", "España", "Chile", "Colombia", "Perú", "Ecuador", "Uruguay", "Paraguay", "Bolivia"]

sql = "INSERT INTO aflix.usuarios (USUARIOS_ID, NOMBRE, APELLIDO, EMAIL, CONTRASENIA, FECHA_NACIMIENTO, PAIS, TERMINOS_CONDICIONES, ROLES_ID, GENERO_PELICULAS_ID_1, GENERO_PELICULAS_ID_2, GENERO_PELICULAS_ID_3, GENERO_PELICULAS_ID_4, GENERO_PELICULAS_ID_5) VALUES\n"

for i in range(1, 301):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    email = f"{nombre.lower()}.{apellido.lower()}{i}@correo.com"
    contrasenia = "Admin1234"
    fecha_nacimiento = f"{random.randint(1970, 2000)}-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}"
    pais = random.choice(paises)
    terminos = True

    sql += f"({i}, '{nombre}', '{apellido}', '{email}', '{contrasenia}', '{fecha_nacimiento}', '{pais}', {terminos}, NULL, NULL, NULL, NULL, NULL),\n"

sql = sql.rstrip(",\n") + ";"

print(sql)

"""CREACIÓN USUARIOS CLIENTES"""

import random

# Datos de ejemplo
nombres = ["Federico", "Sabrina", "Silvana", "Walter", "Sonia", "Jimena", "Fabiana", "Milagros", "Jazmin", "Santiago"]
apellidos = ["Gutierrez", "Palena", "Fullone", "Escobar", "Umpierrez", "Garaban", "Valderrama", "Bagnis", "Arias", "Toledo"]
paises = ["Argentina", "México", "España", "Chile", "Colombia", "Perú", "Ecuador", "Uruguay", "Paraguay", "Bolivia"]

sql = "INSERT INTO aflix.usuarios (USUARIOS_ID, NOMBRE, APELLIDO, EMAIL, CONTRASENIA, FECHA_NACIMIENTO, PAIS, TERMINOS_CONDICIONES, ROLES_ID, GENERO_PELICULAS_ID_1, GENERO_PELICULAS_ID_2, GENERO_PELICULAS_ID_3, GENERO_PELICULAS_ID_4, GENERO_PELICULAS_ID_5) VALUES\n"

for i in range(301, 10001):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    email = f"{nombre.lower()}.{apellido.lower()}{i}@correo.com"
    contrasenia = "Cliente1234"
    fecha_nacimiento = f"{random.randint(1970, 2000)}-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}"
    pais = random.choice(paises)
    terminos = True

    generos = random.sample(range(1, 12), 5)

    sql += f"({i}, '{nombre}', '{apellido}', '{email}', '{contrasenia}', '{fecha_nacimiento}', '{pais}', {terminos}, 2, {generos[0]}, {generos[1]}, {generos[2]}, {generos[3]}, {generos[4]}),\n"

# Quitar la última coma y cerrar la consulta
sql = sql.rstrip(",\n") + ";"

print(sql)  # Copia y pega esto en tu gestor de base de datos

