-- CREACIÓN DE STORED PROCEDURE --

-- 01. Creación de Stored Procedure para agregar una nueva película
DELIMITER $$
CREATE PROCEDURE aflix.agregar_pelicula (
    IN p_CATALOGO_ID INT,
    IN p_NOMBRES TEXT,
    IN p_DESCRIPCION TEXT,
    IN p_IMG TEXT,
    IN p_ACLAMADO TINYINT,
    IN p_GENERO_PELICULAS_ID INT,
    IN p_DIRECTOR TEXT,
    IN p_ESCRITOR TEXT,
    IN p_DURACION TEXT,
    IN p_IDIOMA TEXT,
    IN p_TRAILER TEXT,
    IN p_ESTRENO TEXT,
    IN p_RECAUDACION TEXT,
    IN p_PRESUPUESTO TEXT,
    IN p_BANNER TEXT
)
BEGIN
    INSERT INTO aflix.CATALOGO (
        CATALOGO_ID, NOMBRES, DESCRIPCION, IMG, ACLAMADO, GENERO_PELICULAS_ID,
        DIRECTOR, ESCRITOR, DURACION, IDIOMA, TRAILER,
        ESTRENO, RECAUDACION, PRESUPUESTO, BANNER
    )
    VALUES (
        p_CATALOGO_ID, p_NOMBRES, p_DESCRIPCION, p_IMG, p_ACLAMADO, p_GENERO_PELICULAS_ID,
        p_DIRECTOR, p_ESCRITOR, p_DURACION, p_IDIOMA, p_TRAILER,
        p_ESTRENO, p_RECAUDACION, p_PRESUPUESTO, p_BANNER
    );
END $$
DELIMITER ;

-- 02. Creación de Stored Procedure para actualizar un usuario
DELIMITER $$
CREATE PROCEDURE aflix.actualizar_usuario (
    IN p_USUARIOS_ID INT,
    IN p_NOMBRE VARCHAR(255),
    IN p_APELLIDO VARCHAR(255),
    IN p_EMAIL VARCHAR(255),
    IN p_CONTRASENIA VARCHAR(255),
    IN p_FECHA_NACIMIENTO DATE,
    IN p_PAIS VARCHAR(20),
    IN p_TERMINOS_CONDICIONES TINYINT,
    IN p_ROLES_ID INT
)
BEGIN
    UPDATE aflix.USUARIOS
    SET 
        NOMBRE = p_NOMBRE,
        APELLIDO = p_APELLIDO,
        EMAIL = p_EMAIL,
        CONTRASENIA = p_CONTRASENIA,
        FECHA_NACIMIENTO = p_FECHA_NACIMIENTO,
        PAIS = p_PAIS,
        TERMINOS_CONDICIONES = p_TERMINOS_CONDICIONES,
        ROLES_ID = p_ROLES_ID
    WHERE USUARIOS_ID = p_USUARIOS_ID;
END $$
DELIMITER ;

-- 03. Creación de Stored Procedure para eliminar una película
DELIMITER $$
CREATE PROCEDURE aflix.eliminar_pelicula (
    IN p_CATALOGO_ID INT
)
BEGIN
    DELETE FROM aflix.CATALOGO
    WHERE CATALOGO_ID = p_CATALOGO_ID;
END $$
DELIMITER ;